package org.teamapps.application.api.privilege;

public enum PrivilegeGroupType {


	SIMPLE_PRIVILEGE,
	SIMPLE_ORGANIZATIONAL_PRIVILEGE,
	SIMPLE_CUSTOM_OBJECT_PRIVILEGE,

	STANDARD_PRIVILEGE_GROUP,
	ORGANIZATIONAL_PRIVILEGE_GROUP,
	CUSTOM_OBJECT_PRIVILEGE_GROUP,



}
